

// in our AirBnB database
// a property document
// might look like this perhaps:
{
    location: "Peterborough",
    rules: [],
    availability: [],
    has_wifi: false,
    has_kitchen: true,
    has_free_parking: false,
    reviews: []
}


// users
{
    id: "1234",
    name: "irem",
    properties: [],
},
{
    id: "678",
    name: "alex",
    properties: ["beverly hills mansion,"]
}





























// PRODUCTS
// products might be a collection
// a document in the product collection might
//  look like this:
{
    id: "667",
    SKU: "123",
    name: "blue shoe"
    gender: "unisex",
    category: "shoes",
}
{
    id: "668", // <-- autogenerated
    SKU: "sdafasfdsfsdf",
    name: "red shoe",
}

// USERS
// users collection
// a document in the users collection
//  may look like this:
{
    id: "12312",
    name: "alex"
    email: "alex@alex.com",
    visa: "12345",
    shipping_address: "123 Roywood",
    cart: [
        {
            product: "667",
            qty: 3,
        },
        {
            product: "668",
            qty: 4,
        }
    ]
}
{
    id: "12312",
    email: "lexi",
    cart: [],
}